Initial commit for azd post
Azure/Cloud-Native pull request #61
Opened 2022-09-13 23:42 UTC by savannahostrowski

2022-09-13 23:44 UTC, savannahostrowski commented
@puicchan PTAL - the post is largely finished with the exception of `pipeline config` (waiting until the fix goes in for the release tomorrow).

@austinauth FYI - for the graphic

2022-09-13 23:48 UTC, savannahostrowski commented on website/blog/2022-09-29/index.md
Insert graphic here.

2022-09-13 23:49 UTC, savannahostrowski commented on website/blog/2022-09-29/index.md
> +**@savannah to finish**
Add screenshots after 9/14

2022-09-14 19:13 UTC, nitya approved these changes
Will *wait to** merge this in and update banner etc. later this week. Feel free to send updates up till publication date

2022-09-20 22:09 UTC, savannahostrowski commented
@puicchan @jongio @austinauth @rajeshkamal5050 @nitya This is now ready for review. Please take a look folks!

2022-09-21 15:05 UTC, puicchan commented
One typo else LGTM.

2022-09-21 15:06 UTC, puicchan requested changes

2022-09-21 15:27 UTC, rajeshkamal5050 commented on website/blog/2022-09-29/index.md
> +    - **An Azure subscription** - the Azure location where your resources will be deployed
the Azure account/subscription used for deploying resources

2022-09-21 15:27 UTC, rajeshkamal5050 commented on website/blog/2022-09-29/index.md
> +  - `infra/` - contains all infrastructure as code (IaC) assets written in [Bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep); includes logic to set up a
callout on support for Terraform?

2022-09-21 15:29 UTC, savannahostrowski commented on website/blog/2022-09-29/index.md
> +    - **An Azure subscription** - the Azure location where your resources will be deployed
Yeah - I copied this from the docs for consistency but I agree. It seems like a mistake that the description for region and sub are the same.

@puicchan Thoughts here?

2022-09-21 15:48 UTC, puicchan commented on website/blog/2022-09-29/index.md
> +    - **An Azure subscription** - the Azure location where your resources will be deployed
In readme, it's 
![image](https://user-images.githubusercontent.com/8701892/191550568-3a4e32a7-ea2d-41b1-a9db-cd425dc9cf4d.png)

2022-09-21 15:54 UTC, savannahostrowski commented on website/blog/2022-09-29/index.md
> +    - **An Azure subscription** - the Azure location where your resources will be deployed
Ah - my bad. I think we should still consider amending that text. We can chat.

2022-09-21 17:03 UTC, jongio commented on website/blog/2022-09-29/index.md
> +When designing the CLI, we wanted the experience to be both flexible and non-magical (no side effects, easy to understand). That being said, we're going to run this all with `azd up` but you could al
By using "that being said, " it feels like you are saying there is magic.  You might want to replace it with "Next" or something like that.

2022-09-21 17:04 UTC, jongio commented on website/blog/2022-09-29/index.md
> +So let's walk through it. On running `azd up --template Azure-Samples/todo-python-mongo-swa-func`, I'm prompted for a couple pieces of information as part of the `azd init` process being run under th
```suggestion
So let's walk through it. On running `azd up -t todo-python-mongo-swa-func`, I'm prompted for a couple pieces of information as part of the `azd init` process being run under the hood:
```

2022-09-21 17:04 UTC, jongio commented on website/blog/2022-09-29/index.md
> +Once that information is provided, `azd` will pull down the code from GitHub and create a `.azure/` in the project root that contains all Azure Developer CLI environment information that you just ent
```suggestion
Once that information is provided, `azd` will pull down the code from GitHub and create a `.azure/` directory in the project root that contains all Azure Developer CLI environment information that you just entered. This directory will be important when it comes time to provision and deploy infrastructure in the next step in the `up` process.
```

2022-09-21 17:05 UTC, jongio commented on website/blog/2022-09-29/index.md
> +The back-end endpoint (`service api`) hosts the specification for the API via the `openapi.json` file that's also in the root of the project template. You can explore the endpoints that are available
We don't hyphen frontend and backend in our docs.

2022-09-21 17:05 UTC, jongio commented on website/blog/2022-09-29/index.md
> +The back-end endpoint (`service api`) hosts the specification for the API via the `openapi.json` file that's also in the root of the project template. You can explore the endpoints that are available
```suggestion
The back-end endpoint (`service api`) hosts the specification for the API via the `openapi.yaml` file that's also in the root of the project template. You can explore the endpoints that are available in the web app here. 
```

2022-09-21 17:06 UTC, jongio commented on website/blog/2022-09-29/index.md
> +In my opinion, it's not enough to _just_ set up the application on Azure! I want to know that my web app is performant and serving my users reliably! I also want to make sure that I'm not inadvertent
```suggestion
In my opinion, it's not enough to _just_ set up the application on Azure! I want to know that my web app is performant and serving my users reliably! I also want to make sure that I'm not inadvertently breaking my application as I continue to make changes to it. Thankfully, the Azure Developer CLI also handles all of this via two additional commands - `azd monitor` and `azd pipeline config`.
```

2022-09-21 17:07 UTC, jongio commented on website/blog/2022-09-29/index.md
> +In my opinion, it's not enough to _just_ set up the application on Azure! I want to know that my web app is performant and serving my users reliably! I also want to make sure that I'm not inadvertent
Prob want to add Azure to anywhere you have Developer CLI

2022-09-21 23:17 UTC, merged